# Data Integration

## Setup

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Data/ds_salaries/Data Science Jobs Salaries.csv', skiprows = 2)
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2021e,EN,FT,Data Science Consultant,54000,EUR,64369,DE,50,DE,L
1,2020,SE,FT,Data Scientist,60000,EUR,68428,GR,100,US,L
2,2021e,EX,FT,Head of Data Science,85000,USD,85000,RU,0,RU,M
3,2021e,EX,FT,Head of Data,230000,USD,230000,RU,50,RU,L
4,2021e,EN,FT,Machine Learning Engineer,125000,USD,125000,US,100,US,S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           245 non-null    object
 1   experience_level    245 non-null    object
 2   employment_type     245 non-null    object
 3   job_title           245 non-null    object
 4   salary              245 non-null    int64
 5   salary_currency     245 non-null    object
 6   salary_in_usd       245 non-null    int64
 7   employee_residence  245 non-null    object
 8   remote_ratio        245 non-null    int64
 9   company_location    245 non-null    object
 10  company_size        245 non-null    object
dtypes: int64(3), object(8)
memory usage: 21.2+ KB

## Concatenation
> Documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

In [4]:
df_1 = df[['company_location','job_title','experience_level','salary_in_usd']].sample(n=5)
df_2 = df[['company_location','job_title','experience_level','salary_in_usd']].sample(n=5)
df_3 = df[['company_location','job_title','experience_level','salary_in_usd']].sample(n=5)

In [5]:
df_1

,company_location,job_title,experience_level,salary_in_usd
180,GB,Data Engineer,MI,66400
111,US,Data Scientist,EN,58000
220,AT,Data Scientist,SE,91237
49,GB,Director of Data Engineering,SE,114125
29,US,Machine Learning Engineer,EN,250000

In [6]:
df_2

,company_location,job_title,experience_level,salary_in_usd
155,CL,Data Scientist,MI,40798
210,US,Computer Vision Engineer,SE,60000
234,HR,Machine Learning Engineer,SE,45618
203,CA,Data Scientist,SE,87961
101,US,Data Engineer,MI,110000

In [7]:
df_3

    company_location                 job_title experience_level  salary_in_usd
197               DE            Data Scientist               EN          62726
229               NL             Data Engineer               MI          45773
241               US  Principal Data Scientist               MI         151000
121               US             Data Engineer               MI          93150
116               US      Staff Data Scientist               SE         105000

In [8]:
df_cat1 = pd.concat([df_1,df_2,df_3], axis=0)
df_cat1

,company_location,job_title,experience_level,salary_in_usd
180,GB,Data Engineer,MI,66400
111,US,Data Scientist,EN,58000
220,AT,Data Scientist,SE,91237
49,GB,Director of Data Engineering,SE,114125
29,US,Machine Learning Engineer,EN,250000
155,CL,Data Scientist,MI,40798
210,US,Computer Vision Engineer,SE,60000
234,HR,Machine Learning Engineer,SE,45618
203,CA,Data Scientist,SE,87961
101,US,Data Engineer,MI,110000
197,DE,Data Scientist,EN,62726
229,NL,Data Engineer,MI,45773
241,US,Principal Data Scientist,MI,151000
121,US,Data Engineer,MI,93150
116,US,Staff Data Scientist,SE,105000

In [9]:
df_cat1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 180 to 116
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   company_location  15 non-null     object
 1   job_title         15 non-null     object
 2   experience_level  15 non-null     object
 3   salary_in_usd     15 non-null     int64
dtypes: int64(1), object(3)
memory usage: 600.0+ bytes

In [10]:
df_cat2 = pd.concat([df_1,df_2,df_3], axis=1)
df_cat2

,company_location,job_title,experience_level,salary_in_usd,company_location,job_title,experience_level,salary_in_usd,company_location,job_title,experience_level,salary_in_usd
180,GB,Data Engineer,MI,66400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,US,Data Scientist,EN,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220,AT,Data Scientist,SE,91237.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,GB,Director of Data Engineering,SE,114125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,US,Machine Learning Engineer,EN,250000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,NaN,NaN,NaN,NaN,CL,Data Scientist,MI,40798.0,NaN,NaN,NaN,NaN
210,NaN,NaN,NaN,NaN,US,Computer Vision Engineer,SE,60000.0,NaN,NaN,NaN,NaN
234,NaN,NaN,NaN,NaN,HR,Machine Learning Engineer,SE,45618.0,NaN,NaN,NaN,NaN
203,NaN,NaN,NaN,NaN,CA,Data Scientist,SE,87961.0,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,US,Data Engineer,MI,110000.0,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE,Data Scientist,EN,62726.0
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NL,Data Engineer,MI,45773.0
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,Principal Data Scientist,MI,151000.0
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,Data Engineer,MI,93150.0
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US,Staff Data Scientist,SE,105000.0

In [11]:
df_cat2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 180 to 116
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   company_location  5 non-null      object
 1   job_title         5 non-null      object
 2   experience_level  5 non-null      object
 3   salary_in_usd     5 non-null      float64
 4   company_location  5 non-null      object
 5   job_title         5 non-null      object
 6   experience_level  5 non-null      object
 7   salary_in_usd     5 non-null      float64
 8   company_location  5 non-null      object
 9   job_title         5 non-null      object
 10  experience_level  5 non-null      object
 11  salary_in_usd     5 non-null      float64
dtypes: float64(3), object(9)
memory usage: 1.5+ KB

## Merging
> Documentation: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html

In [12]:
df_1=df[['company_location','experience_level','salary_in_usd']][0:5]
df_1

  company_location experience_level  salary_in_usd
0               DE               EN          64369
1               US               SE          68428
2               RU               EX          85000
3               RU               EX         230000
4               US               EN         125000

In [13]:
df_2=df[['company_location','job_title','salary_in_usd']][0:5]
df_2

  company_location                  job_title  salary_in_usd
0               DE    Data Science Consultant          64369
1               US             Data Scientist          68428
2               RU       Head of Data Science          85000
3               RU               Head of Data         230000
4               US  Machine Learning Engineer         125000

In [14]:
pd.merge(df_1,df_2,on='company_location',how='inner')

,company_location,experience_level,salary_in_usd_x,job_title,salary_in_usd_y
0,DE,EN,64369,Data Science Consultant,64369
1,US,SE,68428,Data Scientist,68428
2,US,SE,68428,Machine Learning Engineer,125000
3,RU,EX,85000,Head of Data Science,85000
4,RU,EX,85000,Head of Data,230000
5,RU,EX,230000,Head of Data Science,85000
6,RU,EX,230000,Head of Data,230000
7,US,EN,125000,Data Scientist,68428
8,US,EN,125000,Machine Learning Engineer,125000

In [15]:
pd.merge(df_1,df_2,on='company_location',how='inner').drop_duplicates()

,company_location,experience_level,salary_in_usd_x,job_title,salary_in_usd_y
0,DE,EN,64369,Data Science Consultant,64369
1,US,SE,68428,Data Scientist,68428
2,US,SE,68428,Machine Learning Engineer,125000
3,RU,EX,85000,Head of Data Science,85000
4,RU,EX,85000,Head of Data,230000
5,RU,EX,230000,Head of Data Science,85000
6,RU,EX,230000,Head of Data,230000
7,US,EN,125000,Data Scientist,68428
8,US,EN,125000,Machine Learning Engineer,125000

In [16]:
df_3=df[['company_location','job_title','experience_level',]][2:6]
df_3

  company_location                  job_title experience_level
2               RU       Head of Data Science               EX
3               RU               Head of Data               EX
4               US  Machine Learning Engineer               EN
5               US     Data Analytics Manager               SE

In [17]:
pd.merge(df_1,df_3,on='company_location',how='inner').drop_duplicates()

,company_location,experience_level_x,salary_in_usd,job_title,experience_level_y
0,US,SE,68428,Machine Learning Engineer,EN
1,US,SE,68428,Data Analytics Manager,SE
2,RU,EX,85000,Head of Data Science,EX
3,RU,EX,85000,Head of Data,EX
4,RU,EX,230000,Head of Data Science,EX
5,RU,EX,230000,Head of Data,EX
6,US,EN,125000,Machine Learning Engineer,EN
7,US,EN,125000,Data Analytics Manager,SE

In [18]:
pd.merge(df_1,df_3,on='company_location',how='outer').drop_duplicates()

,company_location,experience_level_x,salary_in_usd,job_title,experience_level_y
0,DE,EN,64369,NaN,NaN
1,RU,EX,85000,Head of Data Science,EX
2,RU,EX,85000,Head of Data,EX
3,RU,EX,230000,Head of Data Science,EX
4,RU,EX,230000,Head of Data,EX
5,US,SE,68428,Machine Learning Engineer,EN
6,US,SE,68428,Data Analytics Manager,SE
7,US,EN,125000,Machine Learning Engineer,EN
8,US,EN,125000,Data Analytics Manager,SE

##Joining
> documentation: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html

In [19]:
df_1=df[['experience_level']][0:5]
df_1

  experience_level
0               EN
1               SE
2               EX
3               EX
4               EN

In [20]:
df_2=df[['job_title']][2:7]
df_2

                   job_title
2       Head of Data Science
3               Head of Data
4  Machine Learning Engineer
5     Data Analytics Manager
6         Research Scientist

In [21]:
df_1.join(df_2,how='left').drop_duplicates()

  experience_level                  job_title
0               EN                        NaN
1               SE                        NaN
2               EX       Head of Data Science
3               EX               Head of Data
4               EN  Machine Learning Engineer

In [22]:
df_1.join(df_2,how='right').drop_duplicates()

  experience_level                  job_title
2               EX       Head of Data Science
3               EX               Head of Data
4               EN  Machine Learning Engineer
5              NaN     Data Analytics Manager
6              NaN         Research Scientist

In [23]:
df_1.join(df_2,how='inner').drop_duplicates()

  experience_level                  job_title
2               EX       Head of Data Science
3               EX               Head of Data
4               EN  Machine Learning Engineer

In [24]:
df_1.join(df_2,how='outer').drop_duplicates()

  experience_level                  job_title
0               EN                        NaN
1               SE                        NaN
2               EX       Head of Data Science
3               EX               Head of Data
4               EN  Machine Learning Engineer
5              NaN     Data Analytics Manager
6              NaN         Research Scientist