## Data Integration

In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('Data/Colab/california_housing_test.csv')
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

### Concat

In [6]:
df1 = df[['longitude', 'latitude', 'median_income']].sample(n = 5)
df2 = df[['longitude', 'latitude', 'median_income']].sample(n = 5)
df3 = df[['latitude', 'longitude', 'median_income']].sample(n = 5)

In [7]:
df_concat1 = pd.concat([df1, df2, df3], axis=0)

In [8]:
df_concat1

      longitude  latitude  median_income
1749    -121.01     37.65         2.1969
1663    -117.69     34.07         3.7083
1640    -120.70     35.14         3.5352
2114    -121.41     38.60         2.0471
219     -117.90     33.60         3.6538
2343    -118.35     33.92         2.7500
2581    -122.12     37.69         3.4375
2597    -122.34     37.95         3.6719
2786    -121.84     39.75         1.7284
76      -121.89     37.35         3.2599
1057    -119.73     36.76         3.1000
1465    -117.82     33.79         4.1339
543     -122.04     38.28         3.6760
1321    -122.43     37.73         5.0602
2600    -117.96     33.87         4.7984

In [10]:
df_concat1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 1749 to 2600
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   longitude      15 non-null     float64
 1   latitude       15 non-null     float64
 2   median_income  15 non-null     float64
dtypes: float64(3)
memory usage: 480.0 bytes

In [11]:
df_concat2 = pd.concat([df1, df2, df3], axis = 1)

In [12]:
df_concat2

,longitude,latitude,median_income,longitude,latitude,median_income,latitude,longitude,median_income
1749,-121.01,37.65,2.1969,NaN,NaN,NaN,NaN,NaN,NaN
1663,-117.69,34.07,3.7083,NaN,NaN,NaN,NaN,NaN,NaN
1640,-120.70,35.14,3.5352,NaN,NaN,NaN,NaN,NaN,NaN
2114,-121.41,38.60,2.0471,NaN,NaN,NaN,NaN,NaN,NaN
219,-117.90,33.60,3.6538,NaN,NaN,NaN,NaN,NaN,NaN
2343,NaN,NaN,NaN,-118.35,33.92,2.7500,NaN,NaN,NaN
2581,NaN,NaN,NaN,-122.12,37.69,3.4375,NaN,NaN,NaN
2597,NaN,NaN,NaN,-122.34,37.95,3.6719,NaN,NaN,NaN
2786,NaN,NaN,NaN,-121.84,39.75,1.7284,NaN,NaN,NaN
76,NaN,NaN,NaN,-121.89,37.35,3.2599,NaN,NaN,NaN
1057,NaN,NaN,NaN,NaN,NaN,NaN,36.76,-119.73,3.1000
1465,NaN,NaN,NaN,NaN,NaN,NaN,33.79,-117.82,4.1339
543,NaN,NaN,NaN,NaN,NaN,NaN,38.28,-122.04,3.6760
1321,NaN,NaN,NaN,NaN,NaN,NaN,37.73,-122.43,5.0602
2600,NaN,NaN,NaN,NaN,NaN,NaN,33.87,-117.96,4.7984

In [13]:
df_concat2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 1749 to 2600
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   longitude      5 non-null      float64
 1   latitude       5 non-null      float64
 2   median_income  5 non-null      float64
 3   longitude      5 non-null      float64
 4   latitude       5 non-null      float64
 5   median_income  5 non-null      float64
 6   latitude       5 non-null      float64
 7   longitude      5 non-null      float64
 8   median_income  5 non-null      float64
dtypes: float64(9)
memory usage: 1.2 KB

In [14]:
df1 = df[['longitude']][:5]
df2 = df[['latitude']][:5]
df3 = df[['median_income']][:5]

In [15]:
df_concat1 = pd.concat([df1, df2, df3], axis = 1)
df_concat1

   longitude  latitude  median_income
0    -122.05     37.37         6.6085
1    -118.30     34.26         3.5990
2    -117.81     33.78         5.7934
3    -118.36     33.82         6.1359
4    -119.67     36.33         2.9375

### Merge

In [16]:
df1 = df[['longitude','median_income']][:5]
df1

   longitude  median_income
0    -122.05         6.6085
1    -118.30         3.5990
2    -117.81         5.7934
3    -118.36         6.1359
4    -119.67         2.9375

In [18]:
df2 = df[['longitude','median_house_value']][:5]
df2

   longitude  median_house_value
0    -122.05            344700.0
1    -118.30            176500.0
2    -117.81            270500.0
3    -118.36            330000.0
4    -119.67             81700.0

In [22]:
df_merge1 = pd.merge(df1, df2, on = ['longitude'], how = 'inner')
df_merge1

   longitude  median_income  median_house_value
0    -122.05         6.6085            344700.0
1    -118.30         3.5990            176500.0
2    -117.81         5.7934            270500.0
3    -118.36         6.1359            330000.0
4    -119.67         2.9375             81700.0

In [23]:
df3 = df[['longitude','population']][2:7]
df3

   longitude  population
2    -117.81      1484.0
3    -118.36        49.0
4    -119.67       850.0
5    -119.56       663.0
6    -121.43       604.0

In [26]:
df_merge2 = pd.merge(df_merge1, df3, on=['longitude'], how='inner')
df_merge2

   longitude  median_income  median_house_value  population
0    -117.81         5.7934            270500.0      1484.0
1    -118.36         6.1359            330000.0        49.0
2    -119.67         2.9375             81700.0       850.0

In [28]:
df_merge3 = pd.merge(df_merge1, df3, on=['longitude'], how='left')
df_merge3

   longitude  median_income  median_house_value  population
0    -122.05         6.6085            344700.0         NaN
1    -118.30         3.5990            176500.0         NaN
2    -117.81         5.7934            270500.0      1484.0
3    -118.36         6.1359            330000.0        49.0
4    -119.67         2.9375             81700.0       850.0

In [33]:
df_merge4 = pd.merge(df_merge1, df3, on=['longitude'], how='outer')
df_merge4

   longitude  median_income  median_house_value  population
0    -122.05         6.6085            344700.0         NaN
1    -121.43            NaN                 NaN       604.0
2    -119.67         2.9375             81700.0       850.0
3    -119.56            NaN                 NaN       663.0
4    -118.36         6.1359            330000.0        49.0
5    -118.30         3.5990            176500.0         NaN
6    -117.81         5.7934            270500.0      1484.0

### Join

In [34]:
df1 = df[['longitude']][:5]
df1

   longitude
0    -122.05
1    -118.30
2    -117.81
3    -118.36
4    -119.67

In [35]:
df2 = df[['latitude']][2:7]
df2

   latitude
2     33.78
3     33.82
4     36.33
5     36.51
6     38.63

In [36]:
df1.join(df2, how='left')

   longitude  latitude
0    -122.05       NaN
1    -118.30       NaN
2    -117.81     33.78
3    -118.36     33.82
4    -119.67     36.33